services:
  - type: web
    name: telegram-bot
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_API_ID
        value: <your_api_id>
      - key: TELEGRAM_API_HASH
        value: <your_api_hash>
      - key: TELEGRAM_BOT_TOKEN
        value: <your_bot_token>
      - key: PORT
        value: 8080
